<template>
  <div class='box'>
    <div class='BigLoad'>
      <div class='BigLoad'>
        <div class='loadingio-spinner-ripple-j8j7731ecl'>
          <div class='ldio-rgng8b5tv6'>
            <div></div>
            <div></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang='ts'>
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'BigLoad',
  components: {},
  setup() {
    return {}
  }
})
</script>

<style scoped lang='less'>
.box {
  width: 100%;
  height: 100%;

  position: absolute;

  top: 0;

  bottom: 0;

  left: 0;

  right: 0;

  background: #000;

  opacity: 0.7;

  .BigLoad {
    display: flex;
    justify-content: center;
    margin-top: 5%;
  }
}

@keyframes ldio-rgng8b5tv6 {
  0% {
    top: 96px;
    left: 96px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 18px;
    left: 18px;
    width: 156px;
    height: 156px;
    opacity: 0;
  }
}

.ldio-rgng8b5tv6 div {
  position: absolute;
  border-width: 4px;
  border-style: solid;
  opacity: 1;
  border-radius: 50%;
  animation: ldio-rgng8b5tv6 1s cubic-bezier(0, 0.2, 0.8, 1) infinite;
}

.ldio-rgng8b5tv6 div:nth-child(1) {
  border-color: #1d3f72;
  animation-delay: 0s;
}

.ldio-rgng8b5tv6 div:nth-child(2) {
  border-color: #5699d2;
  animation-delay: -0.5s;
}

.loadingio-spinner-ripple-j8j7731ecl {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}

.ldio-rgng8b5tv6 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}

.ldio-rgng8b5tv6 div {
  box-sizing: content-box;
}

/* generated by https://loading.io/ */
</style>
